name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'

    steps:
      - name: (language/python) Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: (before_install) Upgrade environment
        run: |
          python -m pip install --upgrade pip
      - name: (install) Run install scripts
        run: |
          # install LaTeX requirements for Actions runner
          sudo apt-get install dvipng texlive-latex-extra texlive-fonts-recommended cm-super
          bash scripts/runner/build.sh
      - name: (script) Run tests
        run: |
          python -m pytest
      - name: (after_success) Report code coverage
        run: |
          python -m coverage run -m pytest
          python -m coverage xml
          python -m coverage report
          codecov
