name: Converted Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Upgrade pip
        run: | 
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          sudo apt-get install dvipng texlive-latex-extra texlive-fonts-recommended cm-super  # spellcheck: disable
          bash scripts/travis/build.sh
      - name: Run tests
        run: |
          python -m pytest
      - name: Upload code coverage reports
        run: |
          python -m coverage run -m pytest
          python -m coverage xml
          python -m coverage report
          codecov