name: Upload Nightly to PyPI

on:
  push:
    branches: 
      - nightly

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update Docs
      run: |
        cd scripts
        python docs.py
        cd ..
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Commit Changes
      run: |
        git add .
        git commit -m "Update docs"
        git push origin nightly