name: Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pdoc3
        pip install -r requirements.txt
    - name: Generate documentation
      run: |
        pdoc --html --output-dir docs epispot
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Commit docs
      run: |
        git add .
        git commit -m "Update documentation"
        