name: Upload Nightly to PyPI

on:
  push:
    branches: 
      - master
    paths:
      - setup-nightly.py
      - release.py
      - epispot/*
      - .github/workflows/*
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Install Package Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Change Version Info
      run: |
        python release.py
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Commit Changes
      run: |
        git add .
        git commit -m "New Release"
        git push origin master
    - name: Build & Publish Package as 'epispot-nightly'
      run: |
        python setup-nightly.py sdist bdist_wheel
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
